name: my_clean_news_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  intl: ^0.17.0
  dio: ^5.3.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  flutter_riverpod: ^2.4.9
  fluttertoast: ^8.2.4
  webfeed: ^0.7.0
  url_launcher: ^6.2.5
  url_launcher_android: ^6.0.24
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  smooth_page_indicator: ^1.1.0
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  html: ^0.15.4
  xml: ^5.0.2
  mocktail: ^1.0.2
  flutter_inappwebview: ^6.0.0
  html_unescape: ^2.0.0
  audioplayers: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png
